url:
baseurl:

# Site settings
title: 上恩資訊股份有限公司
email:
description: "媽咪愛團購、MY83 保險網 解決生活中遇到的問題，提供發自內心的溫暖服務 從用戶角度設計網站功能，從消費者的立場提供服務 我們團隊來自台大／Stanford、清大、政大等，並擁有美國 Google 產品開發、創業領域、品牌零售和通路等經驗"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f3b700
  secondary: e89e00
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Alice
  pic: 1
  position: 熱心雞婆的<br>創業媽媽
  experience: 碩士畢業於 Stanford University 資工碩士及管理碩士大學畢業於伊利諾香檳校區資工系，大一大二曾就讀於台大資工系<br><br>Alice曾任職於美國Google總部，擔任Partner Technology Manager，負責YouTube及 Chromebook與策略夥伴相關的產品、技術及團隊組建。<br><br>喜歡旅行，曾經一個人背著背包到南美洲、印度、尼泊爾旅行五個月。人生最大的冒險，不是一個人環遊世界、不是創業，而是生了小孩當了媽媽。相信活著就是要熱血！對我來說人生最熱血的事，就是能夠幫助人。

  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Nancy
  pic: 2
  position: 自稱再買就剁手的<br>千手觀音媽媽
  experience: 大學畢業於政治大學新聞學系<br><br>畢業後不務正業踏入當時正在成長中的醫學美容保養品圈當業務，五年內品牌走出台灣外銷歐美。2007-10年期間派駐北京擔任品牌大中華區業務總監，期間跑遍大陸23個城市。08年成功進入大陸市場LVMH集團通路Sephora，為該通路唯一台灣品牌。<br><br>2010年於上海自行創業開貿易公司，代理台灣品牌及踏入電子商務領域，開立三家關於保養品、母嬰用品的網路商店。2013年懷孕後決定舉家返台，現在新頭銜「霓霓媽」。<br><br>相信意志力決定一切 ，人生態度是認真工作&認真享受，以致終日在美食美酒與瘦身中掙扎。發掘商品最大動力來源為自身對購物的熱情，本著當白老鼠的心情為媽咪們開發好物!

  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: TingYi
  pic: 3
  position: 有少女心的<br>大嬸魂媽媽
  experience: 大學畢業於世新大學新聞學系編輯採訪組<br><br>第一份工作在知名美妝品牌任職，從工讀生、品牌公關、行銷廣告、電子商務，一路做到台灣區行銷暨業務主管，卻在二字頭的尾巴時，突然不確定這是否是一輩子想過的生活，毅然離開近七年的公司，去歐洲玩耍了兩個月，重新思考生活。回台後因為懷孕，跳tone到出版界擔任行銷企劃，期盼能浸淫書香裡，陶冶母女倆的性情(但顯然效果有限)。<br><br>深信「見義勇為」的正義感是人類的普世價值，索性將女兒起名「詠薇」，期望近年內可再湊齊兒子「建毅」。<br><br>喜歡學習新東西，因此具塔羅占卜、光療與水晶美甲、英國巴哈花精這種沒機會派上用場的能力。平時以捉弄女兒、佯裝少女為樂。目前負責商品內容行銷，希望每一個好東西都能找到合適的歸宿。
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Naichuan
  pic: 4
  position: 低溫理性藝文風<br>思考人
  experience: 大學畢業於淡江大學統計系<br><br>大學學統計，透過數字建構出理性邏輯。畢業後卻投入感性的藝文工作，發現在藝術裡不是制式的存在。<br>曾在劇場參與音樂及戲劇製作、宣傳到媒體行銷執行。加入知名美妝品牌負責產品開發、前端採購、與後端物流配送，並籌設大陸辦公室。也參與基金會的設立與營運規劃，執行過多屆文化部數位表演藝術節，統籌專案、組織團隊、規劃製作，並參與跨國合創專案、媒合台灣藝術團隊與國際場館及藝術家共同合作交流。<br><br>經歷從無到有、冒險的刺激，透過冒險而看到新的事物與思維，在不同領域找出新的可能。<br>喜歡認真當下，走出一個平實的獨一無二人生。

  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Benson
  pic: 5
  position: 期許自己是個<br>做實事衝好浪的阿宅
  experience: 大學畢業於清華大學資工系 10 級<br><br>喜歡衝浪。大學畢業後因緣際會下，第一份工作是與朋友和開的公司。熱血地為了理想做過產品、也辛勤地為了現實接過案子。三年後在公司最賺錢的當下，選擇離開舒適圈、加入了上恩，只為了追求更大的舞台與成長。來到了這深具挑戰的海灘，準備追這道屬於他近年來最大的浪！<br><br>相信 Drew Houston 說的 “You only need to be right once.”
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
